apiVersion: apps/v1
kind: Deployment    # D should be capital 
metadata: 
  name: result
  labels:
    app: result 
spec:
  template:
        metadata:
          name: result 
          labels:
            app: result 
        spec:
         containers:
          - name: result 
            image: dockersamples/examplevotingapp_result
            ports:
             - containerPort: 80
               name: result
  replicas: 1
  selector:
    matchLabels:      # L should be capital 
       app: result 