apiVersion: apps/v1
kind: Deployment    # D should be capital 
metadata: 
  name: vote 
  labels:
    app: vote 
spec:
  template:
        metadata:
         name: vote
         labels:
           app: vote 
        spec: 
          containers:
           - name: vote
             image: dockersamples/examplevotingapp_vote
             ports: 
              - containerPort: 80    # p should be capital 
                name: vote
  replicas: 1
  selector:
    matchLabels:      # L should be capital 
       app: vote 